/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import javafx.beans.binding.StringBinding;

public class App {
    protected static Quote[] createJsonObject(String jsonString) {
        //convert the json to a Quote object)
        Gson gson = new GsonBuilder().serializeNulls().create();
        return  gson.fromJson(jsonString, Quote[].class);
    }

        protected static Quote getRandomQuote(String str) {
            Quote[] quotes = createJsonObject(str);

            int randomNumber = (int) Math.floor(Math.random() *  quotes.length);
            return quotes[randomNumber];
        };

    public static void main(String[] args) {
        // read file;
        try {
            BufferedReader reader = new BufferedReader(
                new FileReader("assets/recentquotes.json"));
            StringBuilder str = new StringBuilder();
            String quoteString = reader.readLine();

            while(quoteString != null) {
                str = str.append(quoteString);
                quoteString = reader.readLine();
            }

            System.out.println(getRandomQuote(str.toString()).toString());

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
